### PR TITLE
docs: add .readthedocs.yaml to migrate to RTD v2

### PR DESCRIPTION
**Pull request by giuseppe-steduto**
Closes reanahub/reana#710.

### CODE REVIEW

**Comment by giuseppe-steduto** [comment]
The pipeline is now failing because of an issue with XRootD: https://github.com/xrootd/xrootd/issues/2002
This has been solved by https://github.com/xrootd/xrootd/pull/2025 (and indeed patching `xrootd` with the updated version directly from the xrootd git repository, `pip install git+https://github.com/xrootd/xrootd@a1cd57f08845dd71556219966af9381eace19be8#egg=xrootd`, fixes our problem with the dependencies). The edits haven't been released yet, but will be released soon, with XRootD 5.6.

I propose we wait for the package to be updated, rather than removing the dependency from the pipeline. What do you think?

**Comment by tiborsimko** [comment]
> I propose we wait for the package to be updated, rather than removing the dependency from the pipeline. What do you think?

Note that upgrading XRootD may be touchy, because we don't have a test for Snakemake workflow using XRootD remote inputs officially amongst the DEMO test suite matrix. I have a local examples that is basically running [this blog post example](https://blog.reana.io/posts/2023/kerberos-for-the-whole-workflow/). And in the past it was necessary to play with XRootD versions to make it properly run, see the past pull request https://blog.reana.io/posts/2023/kerberos-for-the-whole-workflow/ So we should beware in case of upgrading XRootD to check this too.

(Alternatively, we can play with various `pip` and `setuptools` etc versions, because this was working well in the past... E.g. check past builds and see which package versions changed and how it may have influenced the failure and then pin them to make the build pass.)

**Comment by mdonadoni** [comment]
FYI, xrootd v5.6.0 was released: https://pypi.org/project/xrootd/5.6.0/

**Review by mdonadoni — APPROVED** [review]
LGTM! I have tested the updated version of xrootd by running this workflow: https://github.com/reanahub/reana-workflow-engine-snakemake/pull/42#discussion_r859837148

**Pull request merged**
